server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-user?serverTimezone=UTC
    username: root
    password: jing
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        cluster-name: SH
        namespace: 65c757a2-6664-4e4d-86a6-5a06617a3b86 # dev环境

mybatis:
  type-aliases-package: com.lee.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.lee: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
pattern:
  name: 本地配置local