server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es?serverTimezone=UTC
    username: root
    password: jing
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 192.168.72.100 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: lee # 用户名
    password: 123 # 密码
logging:
  level:
    com.lee: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lee.hotel.pojo

# ElasticSearch配置
es:
  host: 192.168.72.100
  port: 9200