server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  profiles:
    active: dev # 开发环境 dev
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      discovery:
        namespace: 65c757a2-6664-4e4d-86a6-5a06617a3b86 # dev环境
        cluster-name: SH
    gateway:
      routes: # 网关路由配置
        - id: user-service # 路由id，自定义，只要唯一即可
#          uri: http://127.0.0.1:8081
          uri: lb://userservice
          predicates:
            - Path=/user/**
#          filters: # 过滤器
#            - AddRequestHeader=Truth, hello world! # 添加请求头
        - id: order-service # 路由id，自定义，只要唯一即可
#          uri: http://127.0.0.1:8080
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      default-filters: # 默认过滤项
        - AddRequestHeader=Truth, hello world lee! # 添加请求头

